version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tg-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tg_bot_user
      POSTGRES_PASSWORD: tg_bot_pass
      POSTGRES_DB: tg_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-bot-app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    command: bash -c "pip install -r requirements.txt && python main.py"
    restart: unless-stopped

volumes:
  postgres_data:

